### ISSUE TITLE
Explicit path to executable not used?

### ISSUE THREAD

**Issue by TSSlade** [terrastruct/d2-obsidian#11]
Is there a chance the plugin is not yet actually reading/consuming the path to the executable? I have it installed via ObsidianBRAT and am having the following experience:

![image](https://user-images.githubusercontent.com/3211478/208251232-b703201a-6491-4a40-b787-7fb7289afe9c.png)

Here is the path to my d2 installation on my Mac:

![image](https://user-images.githubusercontent.com/3211478/208251263-0e19d17b-5eea-40c9-975d-ae34526fbbaf.png)

And here's the setting as defined in the d2-obsidian plugin settings:

![image](https://user-images.githubusercontent.com/3211478/208251283-903e409a-928a-47a4-9de8-272b8dd0e36f.png)

Obsidian Insider version 1.1.6, MacOS Ventura 13.1

**Comment by alixander** [comment]
@TSSlade Can you try `/usr/local/bin`?

**Comment by TSSlade** [comment]
...narf. Yep, that did it. Thanks!
