### ISSUE TITLE
Smaller output, or custom size?

### ISSUE THREAD

**Issue by canadaduane** [terrastruct/d2-obsidian#18]
I'm grateful for d2 in Obsidian, as it makes more sense and is easier to use than mermaid--thanks for creating this!

One drawback I'm finding is that the output is very large:

![image](https://user-images.githubusercontent.com/129/211181381-cfb5dcf7-77f0-4fc2-a60b-227bb5b500e6.png)

![image](https://user-images.githubusercontent.com/129/211181355-6a512834-dc2e-40fc-86bd-0dfa223f91cb.png)

Are there parameters I should tweak to make this a more reasonably sized two-box graph?

**Comment by alixander** [comment]
oo we need to add `pad` to settings. https://github.com/terrastruct/d2/pull/431

this would control the whitespace padding around the boundaries of the diagram and should help with the undue size

**Comment by berniexie** [comment]
@canadaduane The latest version of this plugin (1.1.0) now supports the pad option, closing this issue
