### ISSUE TITLE
Ability to scale diagrams

### ISSUE THREAD

**Issue by PWSys** [terrastruct/d2-obsidian#23]
Is it possible to scale a diagram within Obsidian?  

Generated diagrams can span multiple pages when exporting to PDF.  It would be nice to have the ability to scale diagrams similar to the way Obsidian scales images.

**Comment by wangmian7** [comment]
this issue is very important！

**Comment by alixander** [comment]
ok. we'll start on it monday

**Comment by PWSys** [comment]
Thanks!
