### ISSUE TITLE
Failing to update (or re-install)

### ISSUE THREAD

**Issue by alechp** [terrastruct/d2-obsidian#27]
- Previously had D2 installed with Obsidian & was working
- Tried updating D2 because I wanted to see whether the `position/dimension sync` feature worked in the Obsidian pugin
- Failed to update
- Tried uninstalling and reinstalling; failed to install
- Tried restarting; no difference
- Other plugins are working (2 other plugins updated fine)

### Screenshots
<img width="1126" alt="Screenshot 2023-02-28 at 5 12 22 PM" src="https://user-images.githubusercontent.com/3058939/222019434-011c6457-1ef4-4ff1-aa36-71e24d699b47.png">

<img width="223" alt="Screenshot 2023-02-28 at 5 07 42 PM" src="https://user-images.githubusercontent.com/3058939/222019686-694cd545-72cf-4776-8015-84b0d48f6520.png">

<img width="260" alt="Screenshot 2023-02-28 at 5 14 37 PM" src="https://user-images.githubusercontent.com/3058939/222019716-96b20fbd-217e-4ee6-bbd7-c50c32680365.png">

**Comment by berniexie** [comment]
@alechp Sorry about that! Forgot to push the latest release. Should be fixed now!

**Comment by alechp** [comment]
Confirmed; install works now. Thanks @berniexie 
<img width="954" alt="Screenshot 2023-03-01 at 8 57 22 AM" src="https://user-images.githubusercontent.com/3058939/222208817-9b848729-9f1e-4aaa-9bda-c545c6002d28.png">
