### ISSUE TITLE
investigate export to PDF problem

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-obsidian#29]
https://discord.com/channels/1039184639652265985/1039185315685998693/1090204837704106034

<img width="434" alt="Screen Shot 2023-03-28 at 9 53 04 AM" src="https://user-images.githubusercontent.com/3120367/228312382-c7e78c0d-d4b4-4326-87d1-a436dad043ea.png">

**Comment by berniexie** [comment]
Right now the diagrams load fine if the debounce is not there. Maybe we can not debounce the first render so that the exporter gets a guaranteed result back

**Comment by berniexie** [comment]
Potential solution is detect media print + 
```
@media print {
  .Preview__Recompile {
    display: none;
  }
}
```

**Comment by alixander** [comment]
sounds good to me @berniexie
