### ISSUE TITLE
[bug] Extra whitespace at bottom of diagram

### ISSUE THREAD

**Issue by jasal82** [terrastruct/d2-obsidian#38]
When rendering a simple diagram I get a lot of extra space below the diagram. I can see that the actual rendered image has the expected height. The extra spacing must come from the plugin.

![image](https://github.com/terrastruct/d2-obsidian/assets/43233047/67d3b509-4a81-441f-869f-b6534091dabd)

**Comment by jasal82** [comment]
Just found https://github.com/terrastruct/d2-obsidian/pull/32. This seems to be the same issue.

**Comment by russellyeo** [comment]
Also seeing this issue. It seems to me the "Container height" setting is being treated as a fixed height rather than a max height.

**Comment by gavin-ts** [comment]
fixed in #32
