### ISSUE TITLE
[feature request] Consistent zoom level for diagrams

### ISSUE THREAD

**Issue by jasal82** [terrastruct/d2-obsidian#39]
A diagram containing only a few elements is zoomed in quite a lot so that the diagram width fits the available reading width. Once the diagram gets larger the elements seem to get smaller because the zoom level changes to fit everything into the canvas. This is absolutely unpractical because I need the element sizes to be visually consistent across a document. For example, if I have only one package in the first diagram and I want to show the relations to other packages in the second diagram the elements will have different sizes.

![image](https://github.com/terrastruct/d2-obsidian/assets/43233047/a9b27dce-9937-4342-a829-3a3a591e3c61)

Here's PlantUML for comparison:

![image](https://github.com/terrastruct/d2-obsidian/assets/43233047/66ddb463-73e2-430e-9566-1bc05f2f73bb)

**Comment by jasal82** [comment]
I think this somehow relates to https://github.com/terrastruct/d2-obsidian/issues/38 as well. I'd suggest a zoom level or scale parameter in the global configuration and/or command line arguments that - when set to the same value for multiple diagrams - ensures consistent item sizes across the rendered images. Then it should also be no problem to determine the required canvas size in Obsidian by querying the generated image height, so that there is no redundant whitespace below the diagram. Diagrams exceeding the available width should be scrollable horizontally. For maximum customization I'd also suggest an explicit height (and maybe also width) parameter exclusive to the Obsidian plugin (i.e. they are not passed to D2) which control the size of the canvas in the Obsidian document. This could be useful when the height (which would otherwise be deduced from the generated image height) should be reduced. Then there should also be vertical scrolling.

**Comment by jasal82** [comment]
Without this feature the plugin is not useful for me, so I consider it a blocker.

**Comment by gavin-ts** [comment]
#32 keeps the scale consistent (up to max height 800) (assuming the window has sufficient width). I think this essentially resolves this issue, but if there is a need for consistent scale outside of the max-height or otherwise we can re-open this
